USERS_PER_PAGE = 12
AUTOCOMPLETE_LIMIT = 10

USER_NAME_MAX_LENGTH = 124
ABOUT_MAX_LENGTH = 256
PHONE_MAX_LENGTH = 12
SKILL_NAME_MAX_LENGTH = 124

COLOR_BLUE = '#4A90D9'
COLOR_GRAY = '#6B7280'
COLOR_GREEN = '#10B981'
COLOR_AMBER = '#F59E0B'
COLOR_PURPLE = '#8B5CF6'
COLOR_PINK = '#EC4899'
COLOR_TEAL = '#14B8A6'
COLOR_ORANGE = '#F97316'

AVATAR_COLORS = [
    COLOR_BLUE, COLOR_GRAY, COLOR_GREEN, COLOR_AMBER,
    COLOR_PURPLE, COLOR_PINK, COLOR_TEAL, COLOR_ORANGE,
]
AVATAR_SIZE = 200
AVATAR_FONT_SIZE = 90
AVATAR_TEXT_COLOR = 'white'
